name: Node.js CI

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build Docker image
      run: |
        docker build -t your-image-name .
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push your-image-name

    - name: Deploy with Docker
      run: |
        docker pull your-image-name
        docker run -d -p 8080:8080 --name your-container-name your-image-name

    
